# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
_: {
  flake.modules.nixos.boot-hardware = _: {
    # imports = [
    #   (modulesPath + "/installer/scan/not-detected.nix")
    # ];

    # boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
    # boot.kernelModules = ["kvm-amd"];

    # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
