name: Build Nix packages and push to Cachix

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command
            max-jobs = auto
            cores = 0

      - uses: cachix/cachix-action@v16
        with:
          name: illusaen
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build plain local packages
        run: nix-build default.nix -A packages.x86_64-linux

      - name: Build plain NixOS configuration
        run: |
          nix-build --expr '
            let
              api = import ./default.nix;
              configs = api.hostLib.mkNixosConfigurations {
                inherit (api) fleet sources;
              };
            in
              configs.odin.config.system.build.toplevel
          '
